### PR TITLE
Improve "Operation Exceeded..." message

### PR DESCRIPTION
**Pull request by dwrobel**
Improve "Operation Exceeds Your Machine Limits" message with information on which axes the limit were exceeded plus the value of range and working area.

### CODE REVIEW

**Comment by dwrobel** [comment]
Before:
Screenshot From 2024-12-23 14-59-22

After:
Screenshot From 2024-12-23 22-36-56

**Comment by dwrobel** [comment]
My `black` formatter:
```
$ black --version
black, 24.4.2 (compiled: no)
Python (CPython) 3.13.0
```
is reporting the following modifications:

```
$ black ./scripts/addons/cam --line-length=100
reformatted /home/dw/projects/cnc/blendercam/scripts/addons/cam/version.py
reformatted /home/dw/projects/cnc/blendercam/scripts/addons/cam/ui/pie_menu/pie_chains.py
reformatted /home/dw/projects/cnc/blendercam/scripts/addons/cam/ui/pie_menu/pie_operation.py
reformatted /home/dw/projects/cnc/blendercam/scripts/addons/cam/gcode_import_parser.py
reformatted /home/dw/projects/cnc/blendercam/scripts/addons/cam/utilities/image_utils.py

All done! ✨ 🍰 ✨
5 files reformatted, 234 files left unchanged.
```
and neither of those files were modified in this PR.


As per :
```
$ black --help | grep -A7 -- '--required-version' 
  --required-version TEXT         Require a specific version of Black to be
                                  running. This is useful for ensuring that
                                  all contributors to your project are using
                                  the same version, because different versions
                                  of Black may format code a little
                                  differently. This option can be set in a
                                  configuration file for consistent results
                                  across environments.
```
please considre creating a configuration which will include at least: `line-length` and `required-version` options so it will be possible to run `black` without any arguments to achieve a consistent results. Then I might check again whether the `scripts/addons/cam/utilities/bounds_utils.py` file would still require some formatting changes.

**Comment by dwrobel** [comment]
>please considre creating a configuration which will include at least: line-length and required-version

https://github.com/pppalain/blendercam/pull/220 should hopefully address this issue, but it fails on something different.

**Comment by pppalain** [comment]
[https://matrix.to/#/#blendercam:matrix.org](url) 
please come on matrix.  this is where we discuss development and issue.

**Pull request merged**
